export const IPC = {
  recorderStart: "recorder:start",
  recorderPause: "recorder:pause",
  recorderResume: "recorder:resume",
  recorderStop: "recorder:stop",
  recorderStatus: "recorder:status",
  modelHealth: "model:health",
  syncRun: "sync:run",
  syncRetryFailed: "sync:retry-failed",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  recordsList: "records:list",
  recordsPage: "records:page",
  recordsClear: "records:clear",
  dashboardChanged: "dashboard:changed",
  authLogin: "auth:login",
  authStatus: "auth:status",
  authLogout: "auth:logout",
  deviceRegister: "device:register",
  openWebReport: "web-report:open",
  openLogsFolder: "logs:open-folder",
  getLogPath: "logs:get-path"
} as const;
